### PR TITLE
#145 Word "user" renamed to "member" in all places

### PR DESCRIPTION
**Pull request by oscarfr96**

### CODE REVIEW

**Comment by KurnakovMaksim** [comment]
Sorry for my bad requirements, but can you left this files changed:
Goal/src/jiraF.Goal.API/Controllers/GoalController.cs
Goal/src/jiraF.Goal.API/Domain/Dtos/User.cs
Goal/src/jiraF.Goal.API/Domain/GoalModel.cs
Goal/src/jiraF.Goal.API/Dtos/Goal/GoalDto.cs
Goal/src/jiraF.Goal.API/Dtos/UserDto.cs
Goal/src/jiraF.Goal.API/Infrastructure/Data/Repositories/GoalRepository.cs

And all other files please return as they were.

Is it hard for you? If yes, i'll later do it myself.

**Comment by oscarfr96** [comment]
> provided

ok I will do it later, no problem

**Comment by KurnakovMaksim** [comment]
@oscarfr96 Wait, now you renamed all places with "member" word to "user", it's wrong...
Ok, I try to say ease, just revert all your commits, after that rename "user" -> "member" in this files:
`Goal/src/jiraF.Goal.API/Controllers/GoalController.cs`
`Goal/src/jiraF.Goal.API/Domain/Dtos/User.cs`
`Goal/src/jiraF.Goal.API/Domain/GoalModel.cs`
`Goal/src/jiraF.Goal.API/Dtos/Goal/GoalDto.cs`
`Goal/src/jiraF.Goal.API/Dtos/UserDto.cs`
`Goal/src/jiraF.Goal.API/Infrastructure/Data/Repositories/GoalRepository.cs`

Will you do it, please? :)

**Review by KurnakovMaksim — APPROVED** [review]

**Comment by KurnakovMaksim** [comment]
@oscarfr96 I did it myself, but thanks for helping, because you founded files :)

**Pull request merged**
